.TH DB2JSON 1 "November 2014" "db Manual" "db Manual"

.SH NAME
db2json \- Convert db records to JSON records

.SH SYNOPSIS
<data> | \fBdb2json\fR

.SH SUMMARY
\fBdb2json\fR converts db records read from stdin to JSON records and outputs
them to stdout. The output is suitable for processing with the json* commands
included with db.

.SH SEE ALSO
db2sqlite(1)

.SH AUTHOR
Written by Curt Hash.
